# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 904faf40481fba232bdefab4ab62715cc4b182b956255c9963c45c14d40e30bd4f796145f9568729c6cc11a918685b41d35f48804f0c4b3c2db09db55e8ec634

test:
  secret_key_base: cc23a058353d5e7ba9303ece3cda6279890e01f8bb99e6f125a0c158a1aaedabad028471d2894467dc0f8474441ae5de115943335c55b4bf179d845bae483cea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
